
# Data location
[data]
base_path = "/Volumes/funke/data/lightsheet/shroff_c_elegans/post_twitching_neurons"
zarr =  "twisted.zarr"
raw_group = "RegB"
seam_cell_group = "RegA"
seg_group = "CellPose"
manual_tracks_dir = "manual_tracks"
seam_cell_tracks_dir = "seam_cell_tracks"
seg_centers_file = "CellPoseCenters.csv"
time_range = [11, 85]